version: 2

sources:
  - name: erp
    schema: erp_northwind  
    tables:
      - name: employees
        columns:
          - name: employee_id
            tests:
              - unique
              - not_null